import os

GOOD_URLS = [
    "https://www.google.com",
    "https://github.com",
    "https://www.paypal.com",
    "https://www.amazon.com",
    "https://www.hdfcbank.com",
    "https://www.microsoft.com",
    "https://www.apple.com",
    "https://www.netflix.com",
    "https://www.chase.com",
    "https://www.wellsfargo.com",
    "https://www.bankofamerica.com",
    "https://www.wikipedia.org",
    "https://www.twitter.com",
    "https://www.instagram.com",
    "https://www.linkedin.com",
    "https://www.reddit.com",
    "https://www.nytimes.com",
    "https://www.cnn.com",
    "https://www.bbc.com",
    "https://www.adobe.com",
    "https://www.dropbox.com",
    "https://www.slack.com",
    "https://www.spotify.com",
    "https://www.twitch.tv",
    "https://www.zoom.us",
    "https://www.salesforce.com",
    "https://www.oracle.com",
    "https://www.ibm.com",
    "https://www.intel.com",
    "https://www.amd.com",
    "https://www.nvidia.com",
    "https://www.samsung.com",
    "https://www.sony.com",
    "https://www.disney.com",
    "https://www.hulu.com",
    "https://www.vimeo.com",
    "https://www.flickr.com",
    "https://www.pinterest.com",
    "https://www.tumblr.com",
    "https://www.wordpress.org",
    "https://www.shopify.com",
    "https://www.squarespace.com",
    "https://www.wix.com",
    "https://www.godaddy.com",
    "https://www.namecheap.com",
    "https://www.cloudflare.com",
    "https://www.fastly.com",
    "https://www.akamai.com",
    "https://www.aws.amazon.com",
    "https://cloud.google.com",
]

BAD_URLS = [
    "http://paypa1-security.com.login.xyz",
    "https://amaz0n-deals.tk/secure-login",
    "http://sbibank-verification.ga/update",
    "https://netflix-billing.ml/confirm",
    "https://whatsapp-update.top/whatsapp",
    "http://192.168.1.100/login",
    "http://g00gle-accounts.cf/signin",
    "https://apple-id-recovery.gq/verify",
    "http://chase-bank-secure.buzz/login",
    "https://wells-fargo-alert.club/account",
    "http://bankofamerica-update.info/secure",
    "https://microsoft-office365.site/login",
    "http://yahoo-mail-recovery.online/verify",
    "https://facebook-security.website/checkpoint",
    "http://instagram-verify-badge.link/login",
    "https://twitter-support.click/auth",
    "http://linkedin-jobs.surf/signin",
    "https://paypal.com-secure.xyz/login",
    "http://amazon.com-offers.icu/claim",
    "https://netflix.com-billing.top/update",
    "http://apple.com-support.tk/verify",
    "https://microsoft.com-login.ml/auth",
    "http://google.com-accounts.ga/recovery",
    "https://yahoo.com-mail.cf/login",
    "http://chase.com-secure.gq/signin",
    "https://wellsfargo.com-alert.buzz/verify",
    "http://bankofamerica.com-update.club/login",
    "https://facebook.com-security.info/checkpoint",
    "http://instagram.com-verify.site/auth",
    "https://twitter.com-support.online/login",
    "http://linkedin.com-jobs.website/signin",
    "https://paypal-secure-login.trycloudflare.com",
    "http://amazon-deals.ngrok.io",
    "https://netflix-billing.ngrok-free.app",
    "http://apple-id-recovery.ngrok.app",
    "https://microsoft-office365.workers.dev",
    "http://google-accounts.pages.dev",
    "https://yahoo-mail-recovery.netlify.app",
    "http://chase-bank-secure.vercel.app",
    "https://wells-fargo-alert.herokuapp.com",
    "http://bankofamerica-update.glitch.me",
    "https://facebook-security.repl.co",
    "http://instagram-verify.replit.dev",
    "https://twitter-support.firebaseapp.com",
    "http://linkedin-jobs.web.app",
    "https://paypal-secure-login.onrender.com",
    "http://amazon-deals.fly.dev",
    "https://netflix-billing.railway.app",
    "http://apple-id-recovery.surge.sh",
    "https://microsoft-office365.000webhostapp.com",
]

def main():
    os.makedirs('ml-retrain/data', exist_ok=True)
    with open('ml-retrain/data/golden_set.txt', 'w') as f:
        for url in GOOD_URLS:
            f.write(f"GOOD:{url}\n")
        for url in BAD_URLS:
            f.write(f"BAD:{url}\n")
    print("ml-retrain/data/golden_set.txt created with 50 GOOD and 50 BAD URLs.")

if __name__ == '__main__':
    main()
